---
### Training parameters ###
latent_size: 32
n_replay: 5000 # per class
epochs: 2
batch_size: 128
dataset: 'MNIST'
balanced: false
softmax: false
arch_specific: 'Conv'
arch_encoder: 'Conv'
arch_decoder: 'Conv'
lr_specific: 2e-4
lr_classifier: 2e-4
lr_autoencoder: 1e-3 
### Logging parameters ###
root: 'Results'
runs: 1
plt_path: 'Plots'
exp_name: ''
