---
### Training parameters ###
latent_size: 32
n_replay: 5000 # per class
batch_size: 128
dataset: 'MNIST'
epochs: 5
root: 'Results'
specific_arch: 'MLP'
encoder_arch: 'IRCL'
decoder_arch: 'IRCL'
specific_lr: 2e-4
classifier_lr: 1e-3
autoencoder_lr: 1e-3 
runs: 1
plt_path: 'Plots'
exp_name: 'Test'
