---
### Training parameters ###
use_amp: false
decoupled_cvae_training: true
latent_size: 32
n_replay: 5000 # per class
epochs: 2 # used only if decoupled_cvae_training is false
epochs_cvae: 50
epochs_classifier: 5
specific_size: 20
batch_size: 128
dataset: 'MNIST'
balanced: false
softmax: false
arch_specific: 'Conv'
arch_encoder: 'Conv'
arch_decoder: 'Conv'
lr_specific: 2e-4
lr_classifier: 2e-4
lr_autoencoder: 1e-3 
lr_discriminator: 2e-4
early_stop_count_vae: 100
early_stop_count_cls: 100
### Logging parameters ###
plot_tsne: false
save_images: true
root: 'Results'
runs: 1
plt_path: 'Plots'
exp_name: ''
