---
### Training parameters ###
latent_size: 32
n_replay: 5000 # per class
epochs: 10
batch_size: 128
dataset: 'MNIST'
balanced: false
softmax: true
specific_arch: 'Conv'
encoder_arch: 'Conv'
decoder_arch: 'Conv'
lr_specific: 2e-4
lr_classifier: 2e-4
lr_autoencoder: 1e-3 
### Logging parameters ###
root: 'Results'
runs: 1
plt_path: 'Plots'
exp_name: ''
